# Generated by Django 4.1.2 on 2022-10-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
